name: CI with PostgreSQL DB Creation from Dump

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres         # Default superuser
          POSTGRES_PASSWORD: testpass      # Superuser password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure the full repo is fetched

    - name: List all files and directories
      run: ls -laR  # List all files and directories, including hidden ones, recursively

    - name: Install PostgreSQL Client
      run: sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Create and Restore Database from Dump
      run: |
        # Create the database from the dump file
        PGPASSWORD=testpass psql -h localhost -U postgres -c "DROP DATABASE IF EXISTS physicaltheraby;"   # Clean existing DB
        PGPASSWORD=testpass psql -h localhost -U postgres -c "CREATE DATABASE physicaltheraby;"
        PGPASSWORD=testpass psql -h localhost -U postgres -d physicaltheraby -f ./database/physicaltheraby.sql  # Ensure correct path
      env:
        PGPASSWORD: testpass

    - name: Set up Node.js (or your preferred language runtime)
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Run Tests
      env:
        DATABASE_URL: postgres://postgres:testpass@localhost:5432/physicaltheraby
      run: |
        npm install
        npm run test
